# Уникальный идентификатор
node.id=0
controller.listener.names=CONTROLLER

# Сервер выполняет обе роли сразу и брокер и контроллер
process.roles=broker,controller

# Список всех серверов kafka 
controller.quorum.voters=0@kafka-server-alpha:9093,1@kafka-server-bravo:9093,2@kafka-server-charlie:9093

# Слушаем и клиентские соединения и соединения с контроллерами
listeners=PLAINTEXT://:9092,CONTROLLER://:9093

# Этот адрес будет сообщем клиентам и остальным брокерам
advertised.listeners=PLAINTEXT://kafka-server-alpha:9092

# Директория сохранения журнала
log.dirs=/data/kafka

