# Уникальный идентификатор сервера
node.id=1

# Сервер выполняет обе роли сразу и брокер и контроллер
process.roles=broker,controller

# Список всех контроллеров kafka, в данном случае это список всех серверов
controller.quorum.voters=0@kafka-server-alpha:9094,1@kafka-server-bravo:9094,2@kafka-server-charlie:9094

# Объявляем три слушателя, один для обслуживания клиентов,
# второй для обслуживания брокеров, и третий для контроллеров
listeners=CLIENT_LISTNER://:9092,BROKER_LISTNER://:9093,KRAFT_CONTROLLER_LISTNER://:9094
controller.listener.names=KRAFT_CONTROLLER_LISTNER
inter.broker.listener.name=BROKER_LISTNER

# Задаем слушателям сетевой протокол PLAINTEXT
listener.security.protocol.map=CLIENT_LISTNER:PLAINTEXT,BROKER_LISTNER:PLAINTEXT,KRAFT_CONTROLLER_LISTNER:PLAINTEXT

# Прокидываем наружу слушатели, что бы клиенты 
# и другие сервера могли подключиться
advertised.listeners=CLIENT_LISTNER://kafka-server-bravo:9092,BROKER_LISTNER://kafka-server-bravo:9093

# Директория сохранения журнала
log.dirs=/data/kafka

