# Уникальный идентификатор сервера
node.id=2

# Сервер выполняет обе роли сразу и брокер и контроллер
process.roles=broker,controller

# Список всех контроллеров kafka, в данном случае это список всех серверов
controller.quorum.voters=0@kafka-server-alpha:9094,1@kafka-server-bravo:9094,2@kafka-server-charlie:9094

# Объявляем три слушателя, один для обслуживания клиентов,
# второй для обслуживания брокеров, и третий для контроллеров
listeners=CLIENT_LISTNER://:9092,BROKER_LISTNER://:9093,KRAFT_CONTROLLER_LISTNER://:9094
controller.listener.names=KRAFT_CONTROLLER_LISTNER
inter.broker.listener.name=BROKER_LISTNER

# Задаем слушателям сетевой протокол PLAINTEXT
listener.security.protocol.map=CLIENT_LISTNER:PLAINTEXT,BROKER_LISTNER:PLAINTEXT,KRAFT_CONTROLLER_LISTNER:PLAINTEXT

# Прокидываем наружу слушатели, что бы клиенты 
# и другие сервера могли подключиться
advertised.listeners=CLIENT_LISTNER://kafka-server-charlie:9092,BROKER_LISTNER://kafka-server-charlie:9093

# Директория сохранения журнала
log.dirs=/data/kafka


# # Уникальный ID узла (должен совпадать с quorum voters)
# node.id=0

# # Роли узла: брокер + контроллер (KRaft)
# process.roles=broker,controller

# # Список всех контроллеров (Raft quorum)
# controller.quorum.voters=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093

# # Слушаем клиентские и controller соединения
# listeners=PLAINTEXT://:9092,CONTROLLER://:9093

# # Что сообщаем клиентам (DNS/host)
# advertised.listeners=PLAINTEXT://kafka-0:9092

# # Соответствие listener → protocol
# listener.security.protocol.map=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT

# # Как брокеры общаются между собой
# inter.broker.listener.name=PLAINTEXT

# # Какой listener используется для Raft
# controller.listener.names=CONTROLLER

# # Где хранятся данные Kafka
# log.dirs=/data/kafka